//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graphics3D.CalcService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputDate3D", Namespace="http://schemas.datacontract.org/2004/07/WcfCalculationLib")]
    [System.SerializableAttribute()]
    public partial class InputDate3D : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][][] Mass_uField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double H {
            get {
                return this.HField;
            }
            set {
                if ((this.HField.Equals(value) != true)) {
                    this.HField = value;
                    this.RaisePropertyChanged("H");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][][] Mass_u {
            get {
                return this.Mass_uField;
            }
            set {
                if ((object.ReferenceEquals(this.Mass_uField, value) != true)) {
                    this.Mass_uField = value;
                    this.RaisePropertyChanged("Mass_u");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Tau {
            get {
                return this.TauField;
            }
            set {
                if ((this.TauField.Equals(value) != true)) {
                    this.TauField = value;
                    this.RaisePropertyChanged("Tau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputDate3D", Namespace="http://schemas.datacontract.org/2004/07/WcfCalculationLib")]
    [System.SerializableAttribute()]
    public partial class OutputDate3D : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][][] Culc_TeploField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][][] Culc_Teplo {
            get {
                return this.Culc_TeploField;
            }
            set {
                if ((object.ReferenceEquals(this.Culc_TeploField, value) != true)) {
                    this.Culc_TeploField = value;
                    this.RaisePropertyChanged("Culc_Teplo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputDate", Namespace="http://schemas.datacontract.org/2004/07/WcfCalculationLib")]
    [System.SerializableAttribute()]
    public partial class InputDate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][] Mass_uField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double H {
            get {
                return this.HField;
            }
            set {
                if ((this.HField.Equals(value) != true)) {
                    this.HField = value;
                    this.RaisePropertyChanged("H");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] Mass_u {
            get {
                return this.Mass_uField;
            }
            set {
                if ((object.ReferenceEquals(this.Mass_uField, value) != true)) {
                    this.Mass_uField = value;
                    this.RaisePropertyChanged("Mass_u");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Tau {
            get {
                return this.TauField;
            }
            set {
                if ((this.TauField.Equals(value) != true)) {
                    this.TauField = value;
                    this.RaisePropertyChanged("Tau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputDate", Namespace="http://schemas.datacontract.org/2004/07/WcfCalculationLib")]
    [System.SerializableAttribute()]
    public partial class OutputDate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][] Culc_TeploField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] Culc_Teplo {
            get {
                return this.Culc_TeploField;
            }
            set {
                if ((object.ReferenceEquals(this.Culc_TeploField, value) != true)) {
                    this.Culc_TeploField = value;
                    this.RaisePropertyChanged("Culc_Teplo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcService.ICalcService")]
    public interface ICalcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CulcTeploParal3D", ReplyAction="http://tempuri.org/ICalcService/CulcTeploParal3DResponse")]
        Graphics3D.CalcService.OutputDate3D CulcTeploParal3D(Graphics3D.CalcService.InputDate3D inputMatrixes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CulcTeploParal3D", ReplyAction="http://tempuri.org/ICalcService/CulcTeploParal3DResponse")]
        System.Threading.Tasks.Task<Graphics3D.CalcService.OutputDate3D> CulcTeploParal3DAsync(Graphics3D.CalcService.InputDate3D inputMatrixes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CulcTeploPosl3D", ReplyAction="http://tempuri.org/ICalcService/CulcTeploPosl3DResponse")]
        Graphics3D.CalcService.OutputDate3D CulcTeploPosl3D(Graphics3D.CalcService.InputDate3D inputMatrixes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CulcTeploPosl3D", ReplyAction="http://tempuri.org/ICalcService/CulcTeploPosl3DResponse")]
        System.Threading.Tasks.Task<Graphics3D.CalcService.OutputDate3D> CulcTeploPosl3DAsync(Graphics3D.CalcService.InputDate3D inputMatrixes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CulcTeploParal", ReplyAction="http://tempuri.org/ICalcService/CulcTeploParalResponse")]
        Graphics3D.CalcService.OutputDate CulcTeploParal(Graphics3D.CalcService.InputDate inputMatrixes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CulcTeploParal", ReplyAction="http://tempuri.org/ICalcService/CulcTeploParalResponse")]
        System.Threading.Tasks.Task<Graphics3D.CalcService.OutputDate> CulcTeploParalAsync(Graphics3D.CalcService.InputDate inputMatrixes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CulcTeploPosl", ReplyAction="http://tempuri.org/ICalcService/CulcTeploPoslResponse")]
        Graphics3D.CalcService.OutputDate CulcTeploPosl(Graphics3D.CalcService.InputDate inputMatrixes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CulcTeploPosl", ReplyAction="http://tempuri.org/ICalcService/CulcTeploPoslResponse")]
        System.Threading.Tasks.Task<Graphics3D.CalcService.OutputDate> CulcTeploPoslAsync(Graphics3D.CalcService.InputDate inputMatrixes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcServiceChannel : Graphics3D.CalcService.ICalcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcServiceClient : System.ServiceModel.ClientBase<Graphics3D.CalcService.ICalcService>, Graphics3D.CalcService.ICalcService {
        
        public CalcServiceClient() {
        }
        
        public CalcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Graphics3D.CalcService.OutputDate3D CulcTeploParal3D(Graphics3D.CalcService.InputDate3D inputMatrixes) {
            return base.Channel.CulcTeploParal3D(inputMatrixes);
        }
        
        public System.Threading.Tasks.Task<Graphics3D.CalcService.OutputDate3D> CulcTeploParal3DAsync(Graphics3D.CalcService.InputDate3D inputMatrixes) {
            return base.Channel.CulcTeploParal3DAsync(inputMatrixes);
        }
        
        public Graphics3D.CalcService.OutputDate3D CulcTeploPosl3D(Graphics3D.CalcService.InputDate3D inputMatrixes) {
            return base.Channel.CulcTeploPosl3D(inputMatrixes);
        }
        
        public System.Threading.Tasks.Task<Graphics3D.CalcService.OutputDate3D> CulcTeploPosl3DAsync(Graphics3D.CalcService.InputDate3D inputMatrixes) {
            return base.Channel.CulcTeploPosl3DAsync(inputMatrixes);
        }
        
        public Graphics3D.CalcService.OutputDate CulcTeploParal(Graphics3D.CalcService.InputDate inputMatrixes) {
            return base.Channel.CulcTeploParal(inputMatrixes);
        }
        
        public System.Threading.Tasks.Task<Graphics3D.CalcService.OutputDate> CulcTeploParalAsync(Graphics3D.CalcService.InputDate inputMatrixes) {
            return base.Channel.CulcTeploParalAsync(inputMatrixes);
        }
        
        public Graphics3D.CalcService.OutputDate CulcTeploPosl(Graphics3D.CalcService.InputDate inputMatrixes) {
            return base.Channel.CulcTeploPosl(inputMatrixes);
        }
        
        public System.Threading.Tasks.Task<Graphics3D.CalcService.OutputDate> CulcTeploPoslAsync(Graphics3D.CalcService.InputDate inputMatrixes) {
            return base.Channel.CulcTeploPoslAsync(inputMatrixes);
        }
    }
}
